### PR TITLE
[BC Break] Change the way we choose the plural form + string replacement

### PR DESCRIPTION
**Pull request by guillaumepotier**
Copy of #66 

- [x] change
- [x] tests
- [x] build
- [x] readme 
- [x] changelog

[GNU Plural forms](https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms)

### CODE REVIEW

**Review by nornagon — APPROVED** [review]
Thanks!

**Comment by nornagon** [comment]
still lgtm :)

**Comment by nornagon** [comment]
Any chance of this being merged & released as a new major?

**Comment by guillaumepotier** [comment]
Sorry @nornagon to have kept you waiting for so long :(

I just merged this PR and created a brand new `v2.0.0` tag. Tell me if it is ok on your side now.

Best

**Comment by cy2-alex** [comment]
It's not on NPM :)

**Comment by guillaumepotier** [comment]
My bad, I published it just now and it appears on npm.js https://www.npmjs.com/package/gettext.js

**Pull request merged**
