### PR TITLE
Test if document is set when reading locale default value

### LINKED ISSUE #7: node.js error
I am getting an error when trying to use this in node.js:

```
/node_modules/gettext.js/lib/gettext.js:10
      locale: document.documentElement.getAttribute('lang') || 'en',
              ^

ReferenceError: document is not defined
```

Looking through the source I'm a bit confused if this ever worked in node.js since it doesn't have a `document` object:
https://github.com/guillaumepotier/gettext.js/blob/master/lib/gettext.js#L10

Can this be removed? Not sure if a default based on browser information is sensible for an isomorphic library.

### PR DESCRIPTION
**Pull request by pokoli**
Fixes #7

### CODE REVIEW

**Comment by pokoli** [comment]
This will allow use to use gettext.js for translation PapaParse error messages. See: https://github.com/mholt/PapaParse/issues/348

Thanks in advance

**Comment by guillaumepotier** [comment]
Sure!

I'll make a release and a tag.

Thanks

**Comment by pokoli** [comment]
@guillaumepotier Thanks for the release. This will help us for sure :+1:

**Comment by andre-f-paggi** [comment]
Hi,
Did you already send it to NPM? :)

**Comment by andre-f-paggi** [comment]
It is still generating an error, even with the newer version:

> ReferenceError: document is not defined
>     at i18n (\node_modules\gettext.js\lib\gettext.js:10:15)

PS: I pasted the new code on the `node_modules `since the newest version is not on NPM yet.

If I check for `this.document` instead of `document` directly seems that solves the problem.

**Pull request merged**
