### PR TITLE
Fix #79 Provided po2json creates empty translations in .json when the…

### LINKED ISSUE #79: Packaged po2json creates empty translations in .json when the string has no translation in .po file and nplurals=1
Because of this ngettext() will return "" instead of English original.

Example .po and generated .json where Thai having translation in .po
```
#: ../client/clock.ts:29 ../client/view.ts:120
msgid "%1 day"
msgid_plural "%1 days"
msgstr[0] "%1 วัน"

    "%1 day": [
        "%1 วัน"
    ],
```

Example .po and generated .json where Chinese having no translation in .po
```
#: ../client/clock.ts:29 ../client/view.ts:120
msgid "%1 day"
msgid_plural "%1 days"
msgstr[0]
 
   "%1 day": [
        ""
    ],
```

### PR DESCRIPTION
**Pull request by gbtami**
… string has no translation in .po file and nplurals=1

### CODE REVIEW

**Comment by guillaumepotier** [comment]
Hi, could you please provide a failing example (I mean, a .po sample file and the .json dumped file).

I just tried this morning with :

```
msgid ""
msgstr ""
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Poedit-KeywordsList: _t;_n:1,2\n"

msgid "one"
msgstr "One"

msgid "two"
msgstr ""

msgid "singular"
msgid_plural "plural"
msgstr[0] "Singular"
msgstr[1] "Plural"

msgid "foo"
msgid_plural "bar"
msgstr[0] ""
msgstr[1] ""
```

and the output I have is the following one:

```
{"":{"plural-forms":"nplurals=2; plural=(n > 1);"},"one":"One","singular":["Singular","Plural"]}
```

I cannot reproduce your case and then add a test for it :)

Best

**Comment by gbtami** [comment]
Sure. The key is "`Plural-Forms: nplurals=1; plural=0;\n"` in the .po header.
You can reproduce it with https://github.com/gbtami/pychess-variants/blob/master/lang/zh_CN/LC_MESSAGES/client.po  (line #317)

Without this PR it produced https://github.com/gbtami/pychess-variants/blob/c95c0c8412b6d4679384d26ffb9b3e57d3f533e4/static/lang/zh_CN/LC_MESSAGES/client.json
(line #52)

**Comment by gbtami** [comment]
May I ask you to publish the new release to NPM please?

**Comment by guillaumepotier** [comment]
Yes indeed, sorry.

Should be done by now.

Best, and thanks again

**Comment by gbtami** [comment]
I'm really sry to bother you again, but your commit "add tests for previous PR" left some garbage lines in bin/po2json script at https://github.com/guillaumepotier/gettext.js/blob/master/bin/po2json#L52
```
<<<<<<< Updated upstream
    if ('' !== jsonData[key][1].length ? jsonData[key][1][0] : jsonData[key][1])
=======
    if ('' !== (jsonData[key][1].length ? jsonData[key][1][0] : jsonData[key][1]))
>>>>>>> Stashed changes
```

**Comment by guillaumepotier** [comment]
I'm deeply sorry for that.

I revolved this conflict and published gettext.js@2.0.2 on npm.

Let me know

Best

**Comment by gbtami** [comment]
Thx a lot!

**Pull request merged**
